<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="OtroAlto.aspx.vb" Inherits="WebApplication6.OtroAlto" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title></title>
</head>
<body>
    <div id="alto">


    <form id="form1" runat="server">
    <div>
    adsadads
        <a href="Testingancho.aspx">testing ancho</a>
        <a href="Testingancho.aspx">Default</a>
         <table>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>

        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>
        <tr>
            <td>
                Algo
            </td>
        </tr>

    </table>
    </div>
    </form>
     </div>
    <script>
        var offsetHeight = document.getElementById('alto').offsetHeight;
        FB.Canvas.setSize({ height: offsetHeight });
    </script>
</body>
</html>