'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Inicio1

    '''<summary>
    '''ver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ver As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LProfileImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LProfileImg As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''historial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents historial As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''proxE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents proxE As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''espacioResAmigos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents espacioResAmigos As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''resAmigos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resAmigos As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''resDigital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resDigital As Global.System.Web.UI.WebControls.HyperLink
End Class
